### ISSUE TITLE
Failed to activate the atom-netconf package

### ISSUE THREAD

**Issue by mksriram** [nokia/atom-netconf#6]
[Enter steps to reproduce:]

1. Just re-installed atom
2. Installed netconf package.

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-netconf](https://github.com/nokia/atom-netconf) package 2.1.0

### Stack Trace

Failed to activate the atom-netconf package

```
At Cannot convert undefined or null to object

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at HTMLDivElement.NetconfToolbar.initialize (/packages/atom-netconf/lib/toolbar-netconf.coffee:93:15)
    at /packages/atom-netconf/lib/netconf.coffee:226:15
    at Array.forEach (<anonymous>)
    at Object.consumeStatusBar (/packages/atom-netconf/lib/netconf.coffee:225:15)
    at Provider.module.exports.Provider.provide (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.activateServices (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/package.js:405:79)
    at Package.activateNow (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/package-manager.js:696:42)
    at /private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (/private/var/folders/wd/v1c46n6569qdycrwhdkw4s4w0000gn/T/AppTranslocation/145D11B7-11FE-4F5E-9CAA-AD2C392F0159/d/Atom.app/Contents/Resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -0:42.9.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-netconf 2.1.0 
```

**Comment by wisotzky** [comment]
Hi Sriram,

very strange, what went wrong in your setup. Since atom-netconf 2.1 the package will create a working directory called ~/workspace_atom_netconf. It will copy a servers.yaml plus an example file into this directory - which allows you to easy work with multiple NETCONF servers. Also is creates a subdirectory called "library" which should be the preferred place to store your own NETCONF examples.

For whatever reason it seems that in your case the directory was created but the servers.yaml file was empty. 

I've just release version 2.2 now, which better copes with such failure scenario. I also will add some sort of tutorial soon, so people have a better idea on how to set all of this up.

/Sven

**Comment by wisotzky** [comment]
Please use version 2.2
